"""add foreignkey in OrderConfirm

Revision ID: 10e7ff843f78
Revises: 6b99160f041c
Create Date: 2022-06-06 14:23:38.768508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10e7ff843f78'
down_revision = '6b99160f041c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('address', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_confirm', 'address', ['address'], ['id'])
    op.drop_column('order_confirm', 'client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('client', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    op.drop_column('order_confirm', 'address')
    # ### end Alembic commands ###
