"""Reset product table

Revision ID: 413ac725ffb0
Revises: 5387f893743d
Create Date: 2022-05-27 17:21:47.458941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '413ac725ffb0'
down_revision = '5387f893743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('group', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('deal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('file', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date_log', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
