"""add name field

Revision ID: 44f979a98587
Revises: b1947a91be73
Create Date: 2022-06-04 17:06:00.194265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f979a98587'
down_revision = 'b1947a91be73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'name')
    # ### end Alembic commands ###
