"""reset file field

Revision ID: 5c49848d04a2
Revises: 7c74d3108a5e
Create Date: 2022-05-27 17:31:30.598268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c49848d04a2'
down_revision = '7c74d3108a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_data', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_data', sa.Column('file', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
