"""add table orderList

Revision ID: 611421693b75
Revises: b3e2e86ebd2c
Create Date: 2022-06-02 17:54:21.879368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611421693b75'
down_revision = 'b3e2e86ebd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=40), nullable=True),
    sa.Column('date_log', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_list')
    # ### end Alembic commands ###
