"""update password

Revision ID: 681d43caed1e
Revises: 407a8cdb7786
Create Date: 2022-06-09 14:49:46.007397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681d43caed1e'
down_revision = '407a8cdb7786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
