"""reset

Revision ID: 6b99160f041c
Revises: 799ddbc2172b
Create Date: 2022-06-06 14:08:40.501340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b99160f041c'
down_revision = '799ddbc2172b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_confirm', 'address')
    op.drop_column('order_confirm', 'district')
    op.drop_column('order_confirm', 'province')
    op.drop_column('order_confirm', 'telephone')
    op.drop_column('order_confirm', 'subDistrict')
    op.drop_column('order_confirm', 'postCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('postCode', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('order_confirm', sa.Column('subDistrict', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('order_confirm', sa.Column('telephone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('order_confirm', sa.Column('province', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('order_confirm', sa.Column('district', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('order_confirm', sa.Column('address', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
