"""add payment field

Revision ID: 7441a3d060d2
Revises: 44f979a98587
Create Date: 2022-06-04 18:04:12.522834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7441a3d060d2'
down_revision = '44f979a98587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('cost', sa.String(length=20), nullable=True),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('serial', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('date_log', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_info')
    # ### end Alembic commands ###
