"""OrderConfirm add ForeignKey

Revision ID: 8baa03f205cc
Revises: f47b1b4f36cf
Create Date: 2022-06-06 16:03:11.528431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8baa03f205cc'
down_revision = 'f47b1b4f36cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_confirm', 'product_data', ['item'], ['id'])
    op.create_foreign_key(None, 'order_confirm', 'address', ['client'], ['id'])
    op.drop_column('order_confirm', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('code', mysql.VARCHAR(length=40), nullable=True))
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    op.drop_column('order_confirm', 'item')
    # ### end Alembic commands ###
