"""add fix choice

Revision ID: 992c9a4752d7
Revises: 7441a3d060d2
Create Date: 2022-06-04 18:08:41.760762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992c9a4752d7'
down_revision = '7441a3d060d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_info', sa.Column('select_choices', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_info', 'select_choices')
    # ### end Alembic commands ###
