"""add address table

Revision ID: b1947a91be73
Revises: 611421693b75
Create Date: 2022-06-04 16:39:58.286032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1947a91be73'
down_revision = '611421693b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('province', sa.String(length=40), nullable=True),
    sa.Column('district', sa.String(length=40), nullable=True),
    sa.Column('subDistrict', sa.String(length=40), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('postCode', sa.String(length=5), nullable=True),
    sa.Column('destination', sa.String(length=10), nullable=True),
    sa.Column('taxName', sa.String(length=100), nullable=True),
    sa.Column('taxPayer', sa.String(length=20), nullable=True),
    sa.Column('taxAddress', sa.String(length=300), nullable=True),
    sa.Column('date_log', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'order_list', ['id'])
    op.create_unique_constraint(None, 'product_data', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'product_data', type_='unique')
    op.drop_constraint(None, 'order_list', type_='unique')
    op.drop_table('address')
    # ### end Alembic commands ###
