"""add acceptence

Revision ID: b3e2e86ebd2c
Revises: 27610b9f313e
Create Date: 2022-06-01 12:28:43.806730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e2e86ebd2c'
down_revision = '27610b9f313e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('accept', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'accept')
    # ### end Alembic commands ###
