"""add foreignkey in OrderConfirm

Revision ID: d2d027519bf9
Revises: b7a9171a0091
Create Date: 2022-06-06 16:22:36.467563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2d027519bf9'
down_revision = 'b7a9171a0091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_confirm', 'address', ['owner'], ['id'])
    op.drop_column('order_confirm', 'client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('client', mysql.VARCHAR(length=40), nullable=True))
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    op.drop_column('order_confirm', 'owner')
    # ### end Alembic commands ###
