"""OrderConfirm add ForeignKey

Revision ID: d7849c7591d3
Revises: 8baa03f205cc
Create Date: 2022-06-06 16:12:47.400498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7849c7591d3'
down_revision = '8baa03f205cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_confirm', 'address', ['client'], ['id'])
    op.drop_column('order_confirm', 'code')
    op.drop_column('order_confirm', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_confirm', sa.Column('code', mysql.VARCHAR(length=40), nullable=True))
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    # ### end Alembic commands ###
