"""add fix field in OrderConfirm

Revision ID: dd4afbcd773c
Revises: 10e7ff843f78
Create Date: 2022-06-06 14:34:12.595120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4afbcd773c'
down_revision = '10e7ff843f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_confirm', 'product_data', ['code'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    # ### end Alembic commands ###
