"""add admin ordered table

Revision ID: dd9dfa3994e5
Revises: 992c9a4752d7
Create Date: 2022-06-04 18:36:41.840847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9dfa3994e5'
down_revision = '992c9a4752d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_confirm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=40), nullable=True),
    sa.Column('date_log', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_confirm')
    # ### end Alembic commands ###
