"""add foreignkey in OrderConfirm

Revision ID: e3cba61ed4c9
Revises: dd4afbcd773c
Create Date: 2022-06-06 14:37:19.701679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cba61ed4c9'
down_revision = 'dd4afbcd773c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_confirm', 'product_data', ['code'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_confirm', type_='foreignkey')
    # ### end Alembic commands ###
