"""reset

Revision ID: f5eca53a4fa9
Revises: d7849c7591d3
Create Date: 2022-06-06 16:16:38.406537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5eca53a4fa9'
down_revision = 'd7849c7591d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_confirm_ibfk_1', 'order_confirm', type_='foreignkey')
    op.drop_column('order_confirm', 'code')
    op.drop_column('order_confirm', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_confirm', sa.Column('address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_confirm', sa.Column('code', mysql.VARCHAR(length=40), nullable=True))
    op.create_foreign_key('order_confirm_ibfk_1', 'order_confirm', 'product_data', ['item'], ['id'])
    # ### end Alembic commands ###
